routes/web.php
<?php
Route::get('/', function () {
    return view('welcome');
});

Route::resource('users', 'UserController');
Route::get('/users', 'UserController@search')->name('users.search');

Route::resource('categories', 'CategoryController');
Route::get('/categories', 'CategoryController@search')->name('categories.search');

Route::resource('books', 'BookController');
Route::get('/books', 'BookController@search')->name('books.search');

Route::resource('orders', 'OrderController');
Route::get('/orders', 'OrderController@search')->name('orders.search');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable=[
    	'title', 'description', 'author', 'publisher', 'price', 'stock', 'cover'
    ];

    public function categories()
    {
    	return $this->belongsToMany('App\Category');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Book;
use App\Category;

class BookController extends Controller
{

    public function index()
    {
        $books = Book::all();
    	return view('books.index', compact('books'));
    }

    public function show($id)
    {
    	$books = Book::findOrFail($id);
        $categories = Category::all();
        return view('books.show', ['books'=>$books, 'categories'=>$categories]);
    }

    public function create()
    {
        $books = Book::all();
        $categories = Category::all();
        return view('books.create', ['books'=>$books, 'categories'=>$categories]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required|min:5|max:50',
            'author'=>'required|max:50',
            'publisher'=>'required|max:50',
            'price'=>'required',
            'stock'=>'required',
            'description'=>'required|max:200',
            'cover'=>'required|image|mimes:jpg,jpeg,png,bmp',
        ]);

        $file = $request->file('cover');
        $path = $file->store('covers', 'public');

        $books = Book::create([
            'title'=>$request->title,
            'author'=>$request->author,
            'publisher'=>$request->publisher,
            'price'=>$request->price,
            'stock'=>$request->stock,
            'description'=>$request->description,
            'cover'=>$path,
        ]);

        $books->categories()->sync($request->categories, false);
        return redirect()->route('books.create')->with('status', 'Book was Successfully Created');
    }

    public function edit($id)
    {
        $books = Book::findOrFail($id);
        $categories = Category::all();
        $cate = array();
        foreach($categories as $cat)
        {
            $cate[$cat->id] = $cat->category_name;
        }

        return view('books.edit', ['books'=>$books, 'categories'=>$categories, 'cate'=>$cate]);
    }

    public function update(Request $request, $id)
    {
        $update_book = Book::findOrfail($id);
        $request->validate([
            'title'         =>'required|min:5|max:50',
            'author'        =>'required|max:50',
            'publisher'     =>'required|max:50',
            'price'         =>'required',
            'stock'         =>'required',
            'description'   =>'required',
            'cover'         =>'required|image|mimes:jpg,jpeg,png,bmp'
        ]);

        $update_book->update([
            'title'       =>$request->title,
            'author'      =>$request->author,
            'publisher'   =>$request->publisher,
            'price'       =>$request->price,
            'stock'       =>$request->stock,
            'description' =>$request->description,
            'cover'       =>$request->cover
        ]);

        if($request->file('cover'))
        {
            if($update_book->cover && file_exists(storage_path('app/public/'.$update_book->cover)))
            {
                Storage::delete('public/'.$update_book->cover);
            }
            $file = $request->file('cover')->store('covers', 'public');
            $update_book->cover = $file;
        }

        $update_book->save();
        $update_book->categories()->sync($request->categories, false);

        return redirect()->route('books.edit', ['books'=>$update_book])->with('status', 'Book was Updated Successfully');
    }

    public function destroy($id)
    {
        $books= Book::findOrfail($id);
        if($books->cover && file_exists(storage_path('app/public/'.$books->coveer)))
        {
            Storage::delete('public/'.$books->cover);
        }
        $books->delete();
        return redirect()->back()->with('status', 'Book was Successfully deleted');
    }

    public function search(Request $request)
    {
        $cari = $request->get('search');
        $books = Book::where('title', 'LIKE', '%'.$cari.'%')->orderBy('created_at', 'DESC')->paginate(5);
        return view('books.index', ['books'=>$books]);
    }
}

resources/views/Books/create.blade.php
@extends('templates.master')

@section('title', 'Create Book')

@section('content')

	<div class="container">
		<h1>Add Book</h1>
		<hr>

		@if (session('status'))
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				<strong> {{ session('status') }} </strong>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		@endif

		<div class="card border-success" style="max-width: 70%; margin: auto; margin-top: 40px;">
			<div class="card-header bg-success text-white">
				<h5>Create a New Book</h5>
			</div>
			<div class="card-body">
				<div class="container text-success">

				<form class="form-group" action="{{ route('books.store') }}" method="POST" enctype="multipart/form-data">
				@csrf

				<div class="row">
					<div class="col-md-3">
						<label  for="title">Title</label>
					</div>
					<div class="col-md-8">
						<input class="form-control {{$errors->first('title')? "is-invalid": ""}}" type="text" name="title" id="title" value="{{old('title')}}">
						<div class="invalid-feedback">
							{{$errors->first('title')}}
						</div>
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-3">
						<label for="author">Author</label>
					</div>
					<div class="col-md-8">
						<input class="form-control {{$errors->first('author')? "is-invalid": ""}}" type="text" name="author" id="author" value="{{old('author')}}">
						<div class="invalid-feedback">
							{{$errors->first('author')}}
						</div>
					</div>
				</div>

			<br>

				<div class="row">
					<div class="col-md-3">
						<label for="publisher">Publisher</label>
					</div>
					<div class="col-md-8">
						<input class="form-control {{$errors->first('publisher')? "is-invalid": ""}}" type="text" name="publisher" id="publisher" value="{{old('publisher')}}">
						<div class="invalid-feedback">
							{{$errors->first('publisher')}}
						</div>
					</div>
				</div>

			<br>

				<div class="row">
					<div class="col-md-3">
						<label for="price">Price</label>
					</div>
					<div class="col-md-8">
						<input class="form-control {{$errors->first('price')? "is-invalid": ""}}" type="number" name="price" id="price">
						<div class="invalid-feedback">
							{{$errors->first('price')}}
						</div>
					</div>
				</div>

			<br>

				<div class="row">
					<div class="col-md-3">
						<label for="stock">Stock</label>
					</div>
					<div class="col-md-8">
						<input class="form-control {{$errors->first('stock')? "is-invalid": ""}}" type="number" name="stock" id="stock">
						<div class="invalid-feedback">
							{{$errors->first('stock')}}
						</div>
					</div>
				</div>

			<br>

				<div class="row">
					<div class="col-md-3">
						<label for="description">Description</label>
					</div>
					<div class="col-md-8">
						<textarea class="form-control {{$errors->first('description')? "is-invalid": ""}}" name="description" id="description" cols="30" rows="10"></textarea>
						<div class="invalid-feedback">
							{{$errors->first('description')}}
						</div>
					</div>
				</div>

			<br>

				<div class="row">
					<div class="col-md-3">
						<label for="categories">Category</label>
					</div>
					<div class="col-md-8">
						<select multiple="" name="categories[]" id="categories" class="form-control {{$errors->first('category_name') ? "is-invalid": ""}}">
							
								@foreach ($categories as $cats)
									<option value="{{$cats->id}}">
										{{$cats->category_name}}
									</option>
								@endforeach

						</select>
						<div class="invalid-feedback">
							{{$errors->first('category_name')}}
						</div>
					</div>
				</div>

			<br>

				<div class="row">
					<div class="input-group mb-3">
						<div class="col-md-3 text-success">
							Cover
						</div>
						<div class="col-md-8">
							<div class="custom-file">
								<input type="file" class="custom-file-input {{$errors->first('cover')? "is-invalid": ""}}" name="cover" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
								<div class="invalid-feedback">
									{{$errors->first('cover')}}
								</div>
								<label class="custom-file-label" for="inputGroupFile01">Cover</label>
							</div>
						</div>
					</div>
				</div>

			<br>

				<div class="row">
					<div class="col-md-3 offset-md-5 offset-md-4">
						<button class="btn btn-outline-success" type="submit">Save</button>
					</div>
				</div>

				</form>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/Books/edit.blade.php
@extends('templates.master')

@section('title', 'Edit Book')

@section('content')

	<div class="container">
		<h1>Edit Book</h1>
		<hr>

		@if (session('status'))
			<div class="alert alert-info alert-dismissible fade show" role="alert">
				<strong> {{ session('status') }} </strong>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		@endif

		<div class="card border-success" style="max-width: 70%; margin: auto; margin-top: 40px;">

		<div class="card-header bg-success text-white">
			<h5> {{ $books['title'] }} </h5>
		</div>

		<div class="card-body">

		<div class="container text-success">
			<form action="{{ route('books.update', $books['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">
			@csrf
			@method('PUT')
		</div>

		<div class="row">
				<div class="col-md-3">
					<label class="text-success" for="title">Title</label>
				</div>
				<div class="col-md-8">					
					<input class="form-control {{$errors->first('title')? "is-invalid": ""}}" type="text" name="title" id="title" value="{{ old('title') ? old('title') : $books['title']}}">
					<div class="invalid-feedback">
						{{$errors->first('title')}}
					</div>
				</div>
			</div>

		<br>

			<div class="row">
				<div class="col-md-3">
					<label class="text-success" for="author">Author</label>
				</div>
				<div class="col-md-8">
					<input class="form-control {{$errors->first('author')? "is-invalid": ""}}" type="text" name="author" id="author" value="{{ old('author') ? old('author') : $books['author'] }}">
					<div class="invalid-feedback">
						{{$errors->first('author')}}
					</div>
				</div>
			</div>

		<br>

			<div class="row">
				<div class="col-md-3">
					<label class="text-success" for="publisher">Publisher</label>
				</div>
				<div class="col-md-8">
					<input class="form-control {{$errors->first('publisher')? "is-invalid": ""}}" type="text" name="publisher" id="publisher" value="{{ old('publisher') ? old('publisher') : $books['publisher'] }}">
					<div class="invalid-feedback">
						{{$errors->first('publisher')}}
					</div>
				</div>
			</div>

		<br>

			<div class="row">
				<div class="col-md-3">
					<label for="price" class="text-success">Price</label>
				</div>
				<div class="col-md-8">
					<input class="form-control {{$errors->first('price')? "is-invalid": ""}}" type="number" name="price" id="price" value="{{ old('price') ? old('price') : $books['price'] }}">
					<div class="invalid-feedback">
						{{$errors->first('price')}}
					</div>
				</div>
			</div>

		<br>

			<div class="row">
				<div class="col-md-3">
					<label for="stock" class="text-success">Stock</label>
				</div>
				<div class="col-md-8">
					<input class="form-control {{$errors->first('stock')? "is-invalid": ""}}" type="number" name="stock" id="stock" value="{{ old('stock') ? old('stock') : $books['stock'] }}">
					<div class="invalid-feedback">
						{{$errors->first('stock')}}
					</div>
				</div>
			</div>

		<br>

			<div class="row">
				<div class="col-md-3">
					<label for="description" class="text-success">Description</label>
				</div>
				<div class="col-md-8">
					<textarea class="form-control {{$errors->first('description')? "is-invalid": ""}}" name="description" id="description" cols="30" rows="10">
						{{ $books['description'] }}
					</textarea>
					<div class="invalid-feedback">
						{{$errors->first('description')}}
					</div>
				</div>
			</div>

		<br>

			<div class="row text-success">
				<div class="col-md-3">
					<label for="categories">Category</label>
				</div>
				<div class="col-md-8">
					<select multiple="" name="categories[]" id="categories" class="form-control {{$errors->first('category_name') ? "is-invalid": ""}}">
							
							@foreach ($categories as $cats)
								<option  {{old('category_name', $cats->categories)==$cats->id ? "selected":''}} value="{{$cats->id}}">
									{{$cats->category_name}}
								</option>
							@endforeach
						</select>
					<div class="invalid-feedback">
						{{$errors->first('category_name')}}
					</div>
				</div>
			</div>

		<br>


			<div class="row">
				<div class="input-group mb-3">
					<div class="col-md-3 text-success">
						Cover
					</div>

					<div class="col-md-8">
						<img src=" {{asset('storage/'.$books['cover'])}} " alt="Cover" class="img-thumbnail" height="150px" width="150px">
						<br><br>
						<div class="custom-file">
							<input type="file" class="custom-file-input {{$errors->first('cover')? "is-invalid": ""}}" name="cover" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01" value="{{ old('cover') }}">
								<div class="invalid-feedback">
									{{$errors->first('cover')}}
								</div>
							<label class="custom-file-label" for="inputGroupFile01">Cover</label>
						</div>
					</div>
				</div>
			</div>

		<br>

			<div class="row">
				<div class="col-md-3 offset-md-5 offset-md-4">
					<button type="submit" class="btn btn-outline-success">Save</button>
				</div>
			</div>

		</form>
	</div>
	
</div>
</div>
</div>
</div>
@endsection

resources/views/Books/index.blade.php
@extends('templates.master')

@section('title', 'List Book')

@section('css')
	<style>
		body{
			padding-top: 30px;
		}
		th, td {
			padding: 10px;
			text-align: center;
		}
		td a{
			margin: 3px;
			align-content: center;
			color: white;
		}
		td a:hover{
			text-decoration: none;
		}
		td button{
			margin-top: 5px;
			cursor: pointer;
		}
		button{
			border: none;
		}
	</style>
@endsection

@section('content')

	<div class="container">
	<h1>Book</h1>
	<hr>

	@if (session('status'))
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			<strong> {{ session('status') }} </strong>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	@endif

		<div class="row">
			<div class="col-md-2">
				<a href=" {{ route('books.create') }} " class="btn btn-outline-success">
					<span data-feather="plus-square"></span> Add book<span class="sr-only">(current)</span>
				</a>
			</div>
			<div class="col-md-8">
				<form action=" {{ route('books.search') }} " method="get">
					<div class="input-group custom-search-form">
						<input type="text" name="search" placeholder="Filter by Title" class="form-control">
						<span class="input-group-btn">&nbsp;
							<button class="btn btn-outline-dark" type="submit">Filter</button>
						</span>
					</div>
				</form>
			</div>
		</div>

	<br>

		<div class="tabel-responsive">
			<table class="table table-hover">
				<thead class="thead-dark">
					<tr>
						<th scope="col">ID</th>
						<th scope="col">Title</th>
						<th scope="col">Author</th>
						<th scope="col">Price</th>
						<th scope="col">Cover</th>
						<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
				@foreach ($books as $book)
					<tr>
						<th>{{ $book['id'] }}</th>
						<td>{{ $book['title'] }}</td>
						<td>{{ $book['author'] }}</td>
						<td>{{ $book['price'] }}</td>
						<td>
							<img src="{{ asset('storage/'.$book['cover']) }}" alt="Cover" width="100px" height="80px">
						</td>
						<td>
							<a href="{{ route('books.show', ['id'=>$book['id']]) }}" class="btn-sm btn-primary">
								<span data-feather="eye"></span> Detail<span class="sr-only">(current)</span>
							</a>
							<a href="{{ route('books.edit', ['id'=>$book['id']]) }}" class="btn-sm btn-success">
								<span data-feather="edit"></span> Edit<span class="sr-only">(current)</span>
							</a>
							<form class="d-inline" onsubmit="return confirm('Permanently Delete Book?')" action="{{ route('books.destroy', ['id'=>$book['id']]) }}" method="POST">
								@csrf
								@method('DELETE')
								<button type="submit" class="btn-sm btn-danger" value="Delete" name="submit">
									<span data-feather="trash"></span> Delete<span class="sr-only">(current)</span>
								</button>
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>

		<div class="pagination justify-content-center"> {{ $books->links() }} </div>

	</div>

@endsection

resources/views/Books/show.blade.php
@extends('templates.master')

@section('title', 'Detail Book')

@section('content')

	<h1>Detail Book</h1>
	<hr>
	
	<div class="card bg-light border-success" style="max-width: 60%; margin: auto; min-height: 500px;">

		<div class="row" style="padding: 25px;">
			<div class="col-md-4 offset-sm-5 offset-md-4">
				&nbsp;&nbsp;<img src=" {{ asset('storage/'.$books['cover']) }} " alt="gambar" style="width:150px; height: 130px;" class="img-thumbnail">
			</div>
		</div>

		<div class="row">
			<div class="col-md-12 text-center">
				<h3>{{ $books['title'] }} </h3>
			</div>
		</div>
		<hr>
		<br>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				<b>ID</b>
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $books['id'] }}
			</div>		
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				<b>Author</b>
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $books['author'] }}
			</div>
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				<b>Publisher</b>
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $books['publisher'] }}
			</div>
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				<b>Price</b>
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $books['price'] }}
			</div>
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				<b>Stock</b>
			</div>
			<div class="col-md-4 col-sm-4">
				{{ $books['stock'] }}
			</div>
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				<b>Category</b>
			</div>
			<div class="col-md-4 col-sm-4">
					@foreach($books->categories as $ct)
						<span class="badge badge-primary"> 
							{{$ct->category_name}}
						</span>
					@endforeach
			</div>
		</div>

		<div class="row">
			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
				<b>Description</b>
			</div>
			<div class="col-md-6 col-sm-8">
				{{ $books['description'] }}
			</div>		
		</div>

	</div>

@endsection