routes/web.php
<?php
Route::get('/', function () {
    return view('welcome');
});

Route::resource('users', 'UserController');
Route::get('/users', 'UserController@search')->name('users.search');

Route::resource('categories', 'CategoryController');
Route::get('/categories', 'CategoryController@search')->name('categories.search');

Route::resource('books', 'BookController');
Route::get('/books', 'BookController@search')->name('books.search');

Route::resource('orders', 'OrderController');
Route::get('/orders', 'OrderController@search')->name('orders.search');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Order extends Model
{
    protected $fillable=[
    	'user_id', 'total_price', 'invoice_number', 'status'
    ];

    public function user()
    {
    	return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use App\User;

class OrderController extends Controller
{
   
    public function index()
    {
    	$orders = Order::all();
        return view('orders.index', compact('orders'));
    }

    public function show($id)
    {
    	$orders = Order::findOrFail($id);
        return view('orders.show', ['orders'=>$orders]);
    }

    public function create()
    {
        $orders = User::all();
        return view('orders.create', ['orders'=>$orders]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'invoice_number'=>'required',
            'user_id'=>'required',
            'total_price'=>'required',
            'status'=>'required',
        ]);

        Order::create([
            'invoice_number'=>$request->invoice_number,
            'user_id'=>$request->user_id,
            'total_price'=>$request->total_price,
            'status'=>$request->status,
        ]);

        return redirect()->route('orders.create')->with('status', 'Order was Successfully Created');
    }

    public function edit($id)
    {
        $orders = Order::findOrFail($id);
        $users = User::all();
        return view('orders.edit', ['orders'=>$orders, 'users'=>$users]);
    }

    public function update(Request $request, $id)
    {
        $update_order = Order::findOrFail($id);
        $request->validate([
            'invoice_number'    =>'required',
            'user_id'           =>'required',
            'total_price'       =>'required',
            'status'            =>'required',
        ]);

        $update_order->update([
            'invoice_number'    =>$request->invoice_number,
            'user_id'           =>$request->user_id,
            'total_price'       =>$request->total_price,
            'status'            =>$request->status,
        ]);

        $update_order->save();
        return redirect()->route('orders.edit',['orders'=>$update_order])->with('status', 'Order was Updated Successfully');
    }

    public function destroy($id)
    {
        $orders = Order::findOrFail($id);
        $orders->delete();
        return redirect()->back()->with('status', 'Order was Successfully deleted');
    }

    public function search(Request $request)
    {
        $cari = $request->get('search');
        $cari2 = $request->get('search2');
        $orders = Order::where('invoice_number', 'LIKE', '%'.$cari.'%')->where('status', 'LIKE', '%'.$cari2.'%')->paginate(5);
        $orders->appends($request->only('search'));

        return view('orders.index', compact('orders'));
    }

}

resources/views/orders/create.blade.php
@extends('templates.master')

@section('title', 'Create order')

@section('content')

	<div class="container">
		<h1>Add order</h1>
		<hr>

		@if (session('status'))
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				<strong> {{ session('status') }} </strong>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		@endif

		<div class="card border-success" style="max-width: 70%; margin: auto; margin-top: 40px;">
			<div class="card-header bg-success text-white">
				<h5>Create a New Order</h5>
			</div>
			<div class="card-body">
				<div class="container text-success">

				<form class="form-group" action="{{ route('orders.store') }}" method="POST" enctype="multipart/form-data">
				@csrf

				<div class="row">
					<div class="col-md-3">
						<label  for="invoice_number">Invoice Number</label>
					</div>
					<div class="col-md-8">
						<input class="form-control {{$errors->first('invoice_number') ? "is-invalid": ""}}" type="text" name="invoice_number" id="invoice_number">
						<div class="invalid-feedback">
							{{$errors->first('invoice_number')}}
						</div>
					</div>
				</div>

			<br>

				<div class="row">
					<div class="col-md-3">
						<label for="user_id">User</label>
					</div>
					<div class="col-md-8">
						<select name="user_id" id="user_id" class="form-control {{$errors->first('user_id') ? "is-invalid": ""}}">
							<option value="">Select User</option>
								@foreach ($orders as $user)
									<option value="{{$user->id}}">
										{{$user->username}}
									</option>
								@endforeach
						</select>
						<div class="invalid-feedback">
							{{$errors->first('user_id')}}
						</div>
					</div>
				</div>

			<br>
				
				<div class="row">
					<div class="col-md-3">
						<label for="total_price">Total Price</label>
					</div>
					<div class="col-md-8">
						<input type="number" name="total_price" id="total_price" class="form-control {{$errors->first('total_price') ? "is-invalid": ""}}">
						<div class="invalid-feedback">
							{{$errors->first('total_price')}}
						</div>
					</div>
				</div>
				
			<br>
				
				<div class="row">
					<div class="col-md-3">
						<label for="status">Status</label>
					</div>
					<div class="col-md-8">
						<select name="status" id="status" class="form-control {{$errors->first('status') ? "is-invalid": ""}}">
							<option value="">Select Status</option>
							<option value="SUBMIT">SUBMIT</option>
							<option value="PROCESS">PROCESS</option>
							<option value="FINISH">FINISH</option>
							<option value="CANCEL">CANCEL</option>
						</select>
					</div>
				</div>
				
				<br>

				<div class="row">
					<div class="col-md-3 offset-md-5 offset-md-4">
						<button class="btn btn-outline-success" type="submit">Save</button>
					</div>
				</div>
				</form>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/orders/edit.blade.php
@extends('templates.master')

@section('title', 'Edit Order')

@section('content')

	<div class="container">
		<h1>Edit Order</h1>
		<hr>

		@if (session('status'))
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				<strong> {{ session('status') }} </strong>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		@endif

		<div class="card border-success" style="max-width: 70%; margin: auto; margin-top: 40px;">

		<div class="card-header bg-success text-white">
			<h5> {{ $orders['invoice_number'] }} </h5>
		</div>

		<div class="card-body">

		<div class="container text-success">
			<form action="{{ route('orders.update', $orders['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">
			@csrf
			@method('PUT')
		</div>

		<div class="row">
				<div class="col-md-3">
					<label class="text-success" for="invoice">Invoice Number</label>
				</div>
				<div class="col-md-8">					
					<input class="form-control {{$errors->first('invoice_number')? "is-invalid": ""}}" type="text" name="invoice_number" id="invoice_number" value="{{ old('invoice_number') ? old('invoice_number') : $orders['invoice_number'] }}">
					<div class="invalid-feedback">
						{{$errors->first('invoice_number')}}
					</div>
				</div>
			</div>

	<br>

			<div class="row">
				<div class="col-md-3">
					<label class="text-success" for="user_id">User</label>
				</div>
				<div class="col-md-8">
					<select name="user_id" id="user_id" class="form-control {{$errors->first('user_id')? "is-invalid": ""}}">
					<option value="">Select User</option>
						@foreach($users as $user)
							<option value=" {{$user->id}} " {{$orders->user_id==$user->id ? "selected":''}}>
								{{$user->username}}
							</option>
						@endforeach
					</select>
					<div class="invalid-feedback">
						{{$errors->first('user_id')}}
					</div>
				</div>
			</div>

		<br>

			<div class="row">
				<div class="col-md-3">
					<label for="total_price" class="text-success">Total Payment</label>
				</div>
				<div class="col-md-8">
					<input class="form-control {{$errors->first('total_price')? "is-invalid": ""}}" type="text" name="total_price" id="total_price" value="{{ $orders['total_price'] }}">
					<div class="invalid-feedback">
						{{$errors->first('total_price')}}
					</div>
				</div>
			</div>

		<br>

			<div class="row">
				<div class="col-md-3">
					<label for="status" class="text-success">Status</label>
				</div>
				<div class="col-md-8">
					<select name="status" id="status" class="form-control {{$errors->first('status') ? "is-invalid": ""}}">
						<option value="">Select Status</option>
						<option {{old('status', $orders->status)=="SUBMIT"? 'selected':''}} value="SUBMIT">SUBMIT</option>
						<option {{old('status', $orders->status)=="PROCESS"? 'selected':''}} value="PROCESS">PROCESS</option>
						<option {{old('status', $orders->status)=="FINISH"? 'selected':''}} value="FINISH">FINISH</option>
						<option {{old('status', $orders->status)=="CANCEL"? 'selected':''}} value="CANCEL">CANCEL</option>
					</select>
					<div class="invalid-feedback">
						{{$errors->first('status')}}
					</div>
				</div>
			</div>

		<br>

			<div class="row">
				<div class="col-md-3 offset-md-5 offset-md-4">
					<button type="submit" class="btn btn-outline-success">Save</button>
				</div>
			</div>

		</form>
	</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/orders/index.blade.php
@extends('templates.master')

@section('title', 'List Order')

@section('css')
	<style>
		body{
			padding-top: 30px;
		}
		th, td {
			padding: 10px;
			text-align: center;
		}
		td a{
			margin: 3px;
			align-content: center;
			color: white;
		}
		td a:hover{
			text-decoration: none;
		}
		td button{
			margin-top: 5px;
			cursor: pointer;
		}
		button{
			border: none;
		}
	</style>
@endsection

@section('content')

	<div class="container">
	<h1>Order</h1>
	<hr>

	@if (session('status'))
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			<strong> {{ session('status') }} </strong>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	@endif

		<div class="row">
			<div class="col-sm-2">
				<a href=" {{ route('orders.create') }} " class="btn btn-outline-success">
					<span data-feather="plus-square"></span> Add Order<span class="sr-only">(current)</span>
				</a>
			</div>
			<div class="col-md-8">
				<form action=" {{ route('orders.search') }} " method="get">
					<div class="input-group custom-search-form">
						<input type="text" name="search" placeholder="Filter by Invoice Number" class="form-control" id="search">
						<select name="search2" class="col-sm-2">
							<option value="">Any</option>
							<option value="SUBMIT">SUBMIT</option>
							<option value="PROCESS">PROCESS</option>
							<option value="FINISH">FINISH</option>
							<option value="CANCEL">CANCEL</option>
						</select>
						<span class="input-group-btn">&nbsp;
							<button class="btn btn-outline-dark" type="submit">Filter</button>
						</span>
					</div>
				</form>
			</div>
		</div>

	<br>

		<div class="tabel-responsive">
			<table class="table table-hover">
				<thead class="thead-dark">
					<tr>
						<th scope="col">ID</th>
						<th scope="col">Invoice Number</th>
						<th scope="col">Total Payment</th>
						<th scope="col">Status</th>
						<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
				@foreach ($orders as $order)
					<tr>
						<th>{{ $order['id'] }}</th>
						<td>{{ $order['invoice_number'] }}</td>
						<td>{{ $order['total_price'] }}</td>
						<td>
							@if($order->status == "SUBMIT")
								<span class="badge badge-primary">{{ $order['status'] }}</span>
							@elseif($order->status == "PROCESS")
								<span class="badge badge-warning">{{ $order['status'] }}</span>
							@elseif($order->status == "FINISH")
								<span class="badge badge-success">{{ $order['status'] }}</span>
							@else
								<span class="badge badge-danger">{{ $order['status'] }}</span>
							@endif
						</td>
						<td>
							<a href="{{ route('orders.show', ['id'=>$order['id']]) }}" class="btn-sm btn-primary">
								<span data-feather="eye"></span> Detail<span class="sr-only">(current)</span>
							</a>
							<a href="{{ route('orders.edit', ['id'=>$order['id']]) }}" class="btn-sm btn-success">
								<span data-feather="edit"></span> Edit<span class="sr-only">(current)</span>
							</a>
							<form class="d-inline" onsubmit="return confirm('Permanently Delete Order?')" action="{{ route('orders.destroy', ['id'=>$order['id']]) }}" method="POST">
								@csrf
								@method('DELETE')
								<button type="submit" class="btn-sm btn-danger" value="Delete" name="submit">
									<span data-feather="trash"></span> Delete<span class="sr-only">(current)</span>
								</button>
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>

		<div class="pagination justify-content-center"> {{ $orders->links() }} </div>
		
	</div>

@endsection

resources/views/orders/show.blade.php
@extends('templates.master')

@section('title', 'Detail Order')

@section('content')

	<h1>Detail Order</h1>
	<hr>
	
	<div class="card bg-light border-success" style="max-width: 70%; margin: auto; min-height: 250px;">
		<div class="row" style="padding: 35px;">
			<div class="col-md-12 text-center">
				<h3>Invoice Number : {{ $orders['invoice_number'] }} </h3>
			</div>
		</div>
		<hr>

		<br>

		<div class="row">
			<div class="col-md-3 offset-md-3 col-sm-3 offset-sm-2">
				<b>User</b>
			</div>
			<div class="col-md-4 col-sm-4">
				&nbsp;{{ $orders->user->username }}
			</div>
			<br>
		</div>
		<div class="row">
			<div class="col-md-3 offset-md-3 col-sm-3 offset-sm-2">
				<b>Total Payment</b>
			</div>
			<div class="col-md-4 col-sm-4">
				&nbsp;{{ $orders['total_price'] }}
			</div>
			<br>
		</div>

		<div class="row">
			<div class="col-md-3 offset-md-3 col-sm-3 offset-sm-2">
				<b>Status</b>
			</div>
			<div class="col-md-4 col-sm-4">
				@if($orders->status == "SUBMIT")
					<span class="badge badge-primary">{{ $orders['status'] }}</span>
				@elseif($orders->status == "PROCESS")
					<span class="badge badge-warning">{{ $orders['status'] }}</span>
				@elseif($orders->status == "FINISH")
					<span class="badge badge-success">{{ $orders['status'] }}</span>
				@else
					<span class="badge badge-danger">{{ $orders['status'] }}</span>
				@endif
			</div>
			<br>
		</div>

	</div>

@endsection